interface SeedMassTime {
  daysOfWeek: number[]
  time: string
  note?: string
}

interface SeedChurch {
  name: string
  slug: string
  address: string
  city: string
  lat: number
  lng: number
  phone?: string
  sourceUrl?: string
  massTimes: SeedMassTime[]
}

const WEEKDAYS = [1, 2, 3, 4, 5]
const SUNDAY = [0]
const SATURDAY = [6]

export const SEED_CHURCHES: SeedChurch[] = [
  {
    name: 'Nhà thờ Đức Bà Sài Gòn',
    slug: 'duc-ba-sai-gon',
    address: '1 Công xã Paris, Bến Nghé, Quận 1, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7797,
    lng: 106.699,
    phone: '028 3822 0477',
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-duc-ba-sai-gon/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:30' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:30' },
      { daysOfWeek: SUNDAY, time: '06:45' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '09:30', note: 'Tiếng Anh' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '17:30' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ Tân Định',
    slug: 'tan-dinh',
    address: '289 Hai Bà Trưng, Phường 8, Quận 3, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7906,
    lng: 106.6883,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-tan-dinh-quan/',
    massTimes: [
      { daysOfWeek: WEEKDAYS, time: '05:00' },
      { daysOfWeek: WEEKDAYS, time: '06:15' },
      { daysOfWeek: WEEKDAYS, time: '17:30' },
      { daysOfWeek: WEEKDAYS, time: '19:00' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '06:15' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '09:00' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '17:30' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Huyện Sỹ (Chợ Đũi)',
    slug: 'huyen-sy',
    address: '1 Tôn Thất Tùng, Quận 1, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.772,
    lng: 106.6912,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-huyen-si-nha-tho-cho-dui/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '06:30' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '09:30' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:00' },
      { daysOfWeek: SUNDAY, time: '19:30' },
    ],
  },
  {
    name: 'Nhà thờ Giáo xứ Gia Định',
    slug: 'gia-dinh',
    address: '280 Bùi Hữu Nghĩa, Phường 2, Bình Thạnh, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.8013,
    lng: 106.6963,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-gia-dinh/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '04:45' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '04:30' },
      { daysOfWeek: SUNDAY, time: '05:30' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '08:30' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ Fatima Bình Triệu',
    slug: 'fatima-binh-trieu',
    address: '69/5 Bình Triệu, Hiệp Bình Chánh, Thủ Đức, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.827,
    lng: 106.7257,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-fatima-binh-trieu/',
    massTimes: [
      { daysOfWeek: WEEKDAYS, time: '05:00' },
      { daysOfWeek: WEEKDAYS, time: '17:30' },
      { daysOfWeek: SATURDAY, time: '18:00', note: 'Lễ vọng Chúa Nhật' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '15:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Đa Minh Ba Chuông',
    slug: 'ba-chuong',
    address: '190 Lê Văn Sỹ, Phường 10, Phú Nhuận, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7944,
    lng: 106.6797,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-da-minh-ba-chuong/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:45' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '06:15' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '09:00' },
      { daysOfWeek: SUNDAY, time: '10:30', note: 'Tiếng Anh' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '17:30' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Đức Mẹ Hằng Cứu Giúp (Kỳ Đồng)',
    slug: 'duc-me-hang-cuu-giup-ky-dong',
    address: '38 Kỳ Đồng, Phường 9, Quận 3, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7857,
    lng: 106.6822,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-duc-me-hang-cuu-giup-ky-dong/',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '06:30' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '10:00' },
      { daysOfWeek: SUNDAY, time: '14:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '18:30' },
      { daysOfWeek: SUNDAY, time: '20:00' },
    ],
  },
  {
    name: 'Nhà thờ Chợ Quán',
    slug: 'cho-quan',
    address: '120 Trần Bình Trọng, Phường 2, Quận 5, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7548,
    lng: 106.6708,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-cho-quan/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '06:30' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:00' },
    ],
  },
  {
    name: "Nhà thờ Thánh Jeanne d'Arc (Ngã Sáu)",
    slug: 'thanh-jeanne-darc',
    address: '116A Hùng Vương, Phường 9, Quận 5, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7541,
    lng: 106.6699,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-thanh-jeanne-darc/',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '09:00' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '18:00' },
    ],
  },
  {
    name: 'Nhà thờ Bùi Phát',
    slug: 'bui-phat',
    address: '1074 Trường Sa, Phường 12, Quận 3, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7902,
    lng: 106.6803,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-bui-phat-quan-3/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '18:00' },
      { daysOfWeek: SATURDAY, time: '16:00', note: 'Lễ vọng Chúa Nhật' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '06:30' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '18:00' },
    ],
  },
  {
    name: 'Nhà thờ Vườn Xoài',
    slug: 'vuon-xoai',
    address: '413 Lê Văn Sỹ, Phường 12, Quận 3, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7902,
    lng: 106.68,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-vuon-xoai/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '06:30' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '17:30' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Hạnh Thông Tây',
    slug: 'hanh-thong-tay',
    address: '53/7 Quang Trung, Phường 11, Gò Vấp, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.8378,
    lng: 106.6677,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-hanh-thong-tay/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '04:45' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '09:30' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '17:30' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Tân Sa Châu',
    slug: 'tan-sa-chau',
    address: '387 Lê Văn Sỹ, Phường 2, Tân Bình, TP.HCM',
    city: 'TP. Hồ Chí Minh',
    lat: 10.7989,
    lng: 106.6651,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-tan-sa-chau/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '18:00' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '10:30' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Hà Nội (Nhà thờ Lớn)',
    slug: 'chinh-toa-ha-noi',
    address: '40 Nhà Chung, Hoàn Kiếm, Hà Nội',
    city: 'Hà Nội',
    lat: 21.0286,
    lng: 105.8497,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-lon-ha-noi/',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '09:00' },
      { daysOfWeek: SUNDAY, time: '11:00' },
      { daysOfWeek: SUNDAY, time: '16:00', note: 'Lễ thiếu nhi' },
      { daysOfWeek: SUNDAY, time: '18:00' },
      { daysOfWeek: SUNDAY, time: '20:00', note: 'Lễ giới trẻ' },
    ],
  },
  {
    name: 'Nhà thờ Cửa Bắc',
    slug: 'cua-bac',
    address: '56 Phan Đình Phùng, Ba Đình, Hà Nội',
    city: 'Hà Nội',
    lat: 21.0438,
    lng: 105.8412,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-cua-bac/',
    massTimes: [
      { daysOfWeek: WEEKDAYS, time: '19:00' },
      { daysOfWeek: SATURDAY, time: '06:30' },
      { daysOfWeek: SATURDAY, time: '19:00', note: 'Lễ vọng Chúa Nhật' },
      { daysOfWeek: SUNDAY, time: '06:30' },
      { daysOfWeek: SUNDAY, time: '08:30', note: 'Lễ thiếu nhi' },
      { daysOfWeek: SUNDAY, time: '10:30', note: 'Tiếng Anh' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Đà Nẵng (Con Gà)',
    slug: 'chinh-toa-da-nang',
    address: '156 Trần Phú, Hải Châu I, Hải Châu, Đà Nẵng',
    city: 'Đà Nẵng',
    lat: 16.0678,
    lng: 108.2208,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chanh-toa-da-nang/',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:15' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '10:00', note: 'Tiếng Anh' },
      { daysOfWeek: SUNDAY, time: '15:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ Chánh tòa Nha Trang (Núi)',
    slug: 'chanh-toa-nha-trang',
    address: '31 Thái Nguyên, Phước Tân, Nha Trang',
    city: 'Nha Trang',
    lat: 12.2459,
    lng: 109.1925,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chanh-toa-nha-trang/',
    massTimes: [
      { daysOfWeek: SATURDAY, time: '17:00', note: 'Lễ vọng Chúa Nhật' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '09:30' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Phủ Cam',
    slug: 'chinh-toa-phu-cam',
    address: '1 Đoàn Hữu Trưng, Phước Vĩnh, TP. Huế',
    city: 'Huế',
    lat: 16.4528,
    lng: 107.5847,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chanh-toa-phu-cam/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '18:30' },
      { daysOfWeek: SUNDAY, time: '05:30' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '15:00' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ đá Phát Diệm',
    slug: 'phat-diem',
    address: 'Thị trấn Phát Diệm, Kim Sơn, Ninh Bình',
    city: 'Ninh Bình',
    lat: 19.9577,
    lng: 106.0879,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-da-phat-diem/',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:00', note: 'Mùa đông 04:45' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Hải Phòng',
    slug: 'chinh-toa-hai-phong',
    address: '46 Hoàng Văn Thụ, Hồng Bàng, Hải Phòng',
    city: 'Hải Phòng',
    lat: 20.86,
    lng: 106.6831,
    sourceUrl: 'https://gphaiphong.org/chi-tiet/gio-le-tai-mot-so-nha-tho-trong-khu-vuc-thanh-thi',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '06:30' },
      { daysOfWeek: SUNDAY, time: '10:00' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Thái Bình',
    slug: 'chinh-toa-thai-binh',
    address: '8 Trần Hưng Đạo, TP. Thái Bình',
    city: 'Thái Bình',
    lat: 20.4463,
    lng: 106.3365,
    sourceUrl: 'https://giaophanthaibinh.net/giao-xu-chinh-toa-thai-binh',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '09:00' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '19:30' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Bùi Chu',
    slug: 'chinh-toa-bui-chu',
    address: 'Xã Xuân Ngọc, Xuân Trường, Nam Định',
    city: 'Nam Định',
    lat: 20.3,
    lng: 106.33,
    sourceUrl:
      'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_ch%C3%ADnh_t%C3%B2a_B%C3%B9i_Chu',
    massTimes: [
      { daysOfWeek: SATURDAY, time: '18:00', note: 'Lễ vọng Chúa Nhật' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Thanh Hóa',
    slug: 'chinh-toa-thanh-hoa',
    address: '232A Trường Thi, TP. Thanh Hóa',
    city: 'Thanh Hóa',
    lat: 19.8067,
    lng: 105.7764,
    sourceUrl: 'https://giaophanthanhhoa.net/nha-tho-chinh-toa.html',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '17:30' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Xã Đoài',
    slug: 'chinh-toa-xa-doai',
    address: 'Xã Nghi Diên, Nghi Lộc, Nghệ An',
    city: 'Vinh',
    lat: 18.745,
    lng: 105.735,
    sourceUrl: 'https://gpvinh.com/giao-hat-chinh-toa-xa-doai',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '07:00', note: 'Mùa đông 07:30' },
      { daysOfWeek: SUNDAY, time: '15:00', note: 'Mùa đông 15:30' },
    ],
  },
  {
    name: 'Trung tâm Thánh Mẫu La Vang',
    slug: 'la-vang',
    address: 'Thôn Phú Hưng, Hải Phú, Hải Lăng, Quảng Trị',
    city: 'Quảng Trị',
    lat: 16.68,
    lng: 107.19,
    sourceUrl: 'https://giothanhle.net/gio-le/trung-tam-hanh-huong-duc-me-la-vang-quang-tri/',
    massTimes: [
      { daysOfWeek: WEEKDAYS, time: '05:00' },
      { daysOfWeek: WEEKDAYS, time: '19:00' },
      { daysOfWeek: SUNDAY, time: '06:00' },
      { daysOfWeek: SUNDAY, time: '15:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Kon Tum (Nhà thờ Gỗ)',
    slug: 'chinh-toa-kon-tum',
    address: '13 Nguyễn Huệ, Thống Nhất, TP. Kon Tum',
    city: 'Kon Tum',
    lat: 14.3545,
    lng: 108.0076,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chinh-toa-kon-tum/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '16:00' },
    ],
  },
  {
    name: 'Nhà thờ Chánh tòa Qui Nhơn (Nhà thờ Nhọn)',
    slug: 'chanh-toa-qui-nhon',
    address: '122 Trần Hưng Đạo, Hải Cảng, TP. Qui Nhơn',
    city: 'Qui Nhơn',
    lat: 13.768,
    lng: 109.224,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chanh-toa-quy-nhon/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '08:30' },
      { daysOfWeek: SUNDAY, time: '17:30' },
    ],
  },
  {
    name: 'Nhà thờ Mằng Lăng',
    slug: 'mang-lang',
    address: 'An Thạch, Tuy An, Phú Yên',
    city: 'Phú Yên',
    lat: 13.273,
    lng: 109.245,
    sourceUrl: 'https://vi.wikipedia.org/wiki/Nh%C3%A0_th%E1%BB%9D_M%E1%BA%B1ng_L%C4%83ng',
    massTimes: [
      { daysOfWeek: WEEKDAYS, time: '18:30' },
      { daysOfWeek: SATURDAY, time: '05:30' },
      { daysOfWeek: SATURDAY, time: '18:30' },
      { daysOfWeek: SUNDAY, time: '05:30' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Buôn Ma Thuột (Thánh Tâm)',
    slug: 'chinh-toa-buon-ma-thuot',
    address: '02 Phan Chu Trinh, Thắng Lợi, TP. Buôn Ma Thuột',
    city: 'Buôn Ma Thuột',
    lat: 12.67,
    lng: 108.05,
    sourceUrl:
      'https://giole.com.vn/danh-sach/dak-lak/chinh-toa-ban-me-thuot-nha-tho-thanh-tam-buon-me-thuot',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:30' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '17:30' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Đà Lạt (Con Gà)',
    slug: 'chinh-toa-da-lat',
    address: '15 Trần Phú, Phường 3, TP. Đà Lạt',
    city: 'Đà Lạt',
    lat: 11.9416,
    lng: 108.4383,
    sourceUrl: 'https://hddmvn.net/gio-le-tai-cac-nha-tho-trong-thanh-pho-da-lat/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:15' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:15' },
      { daysOfWeek: SUNDAY, time: '05:30' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '08:30' },
      { daysOfWeek: SUNDAY, time: '16:00' },
      { daysOfWeek: SUNDAY, time: '18:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Xuân Lộc',
    slug: 'chinh-toa-xuan-loc',
    address: '144 Hùng Vương, Long Khánh, Đồng Nai',
    city: 'Đồng Nai',
    lat: 10.9382,
    lng: 107.2425,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chanh-toa-xuan-loc/',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '04:30' },
      { daysOfWeek: SUNDAY, time: '06:00' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:00' },
      { daysOfWeek: SUNDAY, time: '19:30' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Phan Thiết',
    slug: 'chanh-toa-phan-thiet',
    address: '587 Trần Hưng Đạo, TP. Phan Thiết',
    city: 'Phan Thiết',
    lat: 10.928,
    lng: 108.102,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chanh-toa-phan-thiet/',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Bà Rịa',
    slug: 'chanh-toa-ba-ria',
    address: 'Lê Lợi, Phước Hiệp, TP. Bà Rịa',
    city: 'Bà Rịa',
    lat: 10.4965,
    lng: 107.1684,
    sourceUrl: 'https://www.giaophanbaria.org/van-hoa/cac-gio-cu-hanh-thanh-le-chua-nhat',
    massTimes: [
      { daysOfWeek: SATURDAY, time: '17:30', note: 'Lễ vọng Chúa Nhật' },
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Mỹ Tho',
    slug: 'chinh-toa-my-tho',
    address: '32 Hùng Vương, Phường 7, TP. Mỹ Tho',
    city: 'Mỹ Tho',
    lat: 10.3593,
    lng: 106.3625,
    sourceUrl: 'https://giothanhle.net/gio-le/nha-tho-chinh-toa-my-tho/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:15' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:45' },
      { daysOfWeek: SUNDAY, time: '05:15' },
      { daysOfWeek: SUNDAY, time: '07:30' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:30' },
    ],
  },
  {
    name: 'Nhà thờ Chánh tòa Vĩnh Long',
    slug: 'chanh-toa-vinh-long',
    address: '141 Lý Thái Tổ, Phường 2, TP. Vĩnh Long',
    city: 'Vĩnh Long',
    lat: 10.2497,
    lng: 105.9714,
    sourceUrl: 'https://giothanhle.vn/c/401B1',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:45' },
      { daysOfWeek: SUNDAY, time: '08:00' },
      { daysOfWeek: SUNDAY, time: '16:30' },
      { daysOfWeek: SUNDAY, time: '18:00' },
    ],
  },
  {
    name: 'Nhà thờ Chính tòa Cần Thơ',
    slug: 'chinh-toa-can-tho',
    address: '14 Nguyễn Thị Minh Khai, Ninh Kiều, TP. Cần Thơ',
    city: 'Cần Thơ',
    lat: 10.029,
    lng: 105.782,
    sourceUrl: 'https://giole.com.vn/danh-sach/can-tho/chinh-toa-can-tho',
    massTimes: [
      { daysOfWeek: SUNDAY, time: '05:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
      { daysOfWeek: SUNDAY, time: '19:00' },
    ],
  },
  {
    name: 'Nhà thờ Tắc Sậy (Cha Diệp)',
    slug: 'tac-say',
    address: 'Ấp 2, QL1A, Tân Phong, Giá Rai, Bạc Liêu',
    city: 'Bạc Liêu',
    lat: 9.286,
    lng: 105.494,
    sourceUrl: 'https://namthientravel.com.vn/gio-thanh-le-nha-tho-tac-say-moi-nhat/',
    massTimes: [
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '05:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '09:00' },
      { daysOfWeek: WEEKDAYS.concat(SATURDAY), time: '17:00' },
      { daysOfWeek: SUNDAY, time: '07:00' },
      { daysOfWeek: SUNDAY, time: '09:00' },
      { daysOfWeek: SUNDAY, time: '17:00' },
    ],
  },
]
