export interface Word {
  english: string
  emoji: string
  sentences: string[]
}

export type Level = 'starters' | 'movers' | 'flyers'

export interface LevelInfo {
  id: Level
  name: string
  emoji: string
  description: string
}

export const levels: LevelInfo[] = [
  { id: 'starters', name: 'Starters', emoji: '🌱', description: 'Simple words (3-4 letters)' },
  { id: 'movers', name: 'Movers', emoji: '🚀', description: 'Medium words (4-6 letters)' },
  { id: 'flyers', name: 'Flyers', emoji: '✈️', description: 'Longer words (5-8 letters)' },
]

export interface Category {
  id: string
  name: string
  emoji: string
  words: Record<Level, Word[]>
}

export const categories: Category[] = [
  // ─── ANIMALS ───
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🐾',
    words: {
      starters: [
        { english: 'cat', emoji: '🐱', sentences: ['The cat is sleeping.', 'I have a black cat.'] },
        { english: 'dog', emoji: '🐶', sentences: ['The dog is happy.', 'My dog likes to run.'] },
        { english: 'pig', emoji: '🐷', sentences: ['The pig is pink.', 'A pig lives on a farm.'] },
        { english: 'hen', emoji: '🐔', sentences: ['The hen has eggs.', 'A hen is a bird.'] },
        { english: 'cow', emoji: '🐮', sentences: ['The cow gives milk.', 'I see a big cow.'] },
        { english: 'ant', emoji: '🐜', sentences: ['The ant is small.', 'An ant can carry food.'] },
        { english: 'bat', emoji: '🦇', sentences: ['A bat can fly.', 'The bat sleeps in the day.'] },
        { english: 'fox', emoji: '🦊', sentences: ['The fox is fast.', 'A fox has a long tail.'] },
        { english: 'bee', emoji: '🐝', sentences: ['The bee makes honey.', 'A bee can sting you.'] },
        { english: 'bug', emoji: '🐛', sentences: ['I found a bug.', 'The bug is green.'] },
        { english: 'ram', emoji: '🐏', sentences: ['The ram has big horns.', 'A ram is a male sheep.'] },
        { english: 'owl', emoji: '🦉', sentences: ['The owl can see at night.', 'An owl says hoo.'] },
        { english: 'ape', emoji: '🦍', sentences: ['The ape is big.', 'An ape can climb trees.'] },
        { english: 'emu', emoji: '🐦', sentences: ['The emu is a big bird.', 'An emu cannot fly.'] },
        { english: 'yak', emoji: '🐂', sentences: ['The yak has long hair.', 'A yak lives in the cold.'] },
      ],
      movers: [
        { english: 'fish', emoji: '🐟', sentences: ['The fish swims in water.', 'I caught a big fish.'] },
        { english: 'bird', emoji: '🐦', sentences: ['The bird can sing.', 'A bird has two wings.'] },
        { english: 'duck', emoji: '🦆', sentences: ['The duck swims in the pond.', 'A duck says quack.'] },
        { english: 'frog', emoji: '🐸', sentences: ['The frog can jump high.', 'A frog lives near water.'] },
        { english: 'bear', emoji: '🐻', sentences: ['The bear is very big.', 'A bear likes honey.'] },
        { english: 'lion', emoji: '🦁', sentences: ['The lion is the king.', 'A lion can roar loud.'] },
        { english: 'tiger', emoji: '🐯', sentences: ['The tiger has stripes.', 'A tiger runs very fast.'] },
        { english: 'horse', emoji: '🐴', sentences: ['The horse can run fast.', 'I want to ride a horse.'] },
        { english: 'whale', emoji: '🐋', sentences: ['The whale is very big.', 'A whale lives in the sea.'] },
        { english: 'sheep', emoji: '🐑', sentences: ['The sheep has soft wool.', 'I count sheep to sleep.'] },
        { english: 'goat', emoji: '🐐', sentences: ['The goat eats grass.', 'A goat can climb hills.'] },
        { english: 'mouse', emoji: '🐭', sentences: ['The mouse is tiny.', 'A mouse likes cheese.'] },
        { english: 'snake', emoji: '🐍', sentences: ['The snake has no legs.', 'A snake can be long.'] },
        { english: 'shark', emoji: '🦈', sentences: ['The shark swims fast.', 'A shark has sharp teeth.'] },
        { english: 'panda', emoji: '🐼', sentences: ['The panda is black and white.', 'A panda eats bamboo.'] },
        { english: 'camel', emoji: '🐫', sentences: ['The camel lives in the desert.', 'A camel has a hump.'] },
        { english: 'zebra', emoji: '🦓', sentences: ['The zebra has stripes.', 'A zebra looks like a horse.'] },
      ],
      flyers: [
        { english: 'rabbit', emoji: '🐰', sentences: ['The rabbit has long ears.', 'My rabbit loves carrots.'] },
        { english: 'monkey', emoji: '🐵', sentences: ['The monkey climbs trees.', 'A monkey likes bananas.'] },
        { english: 'penguin', emoji: '🐧', sentences: ['The penguin lives in the cold.', 'A penguin cannot fly.'] },
        { english: 'dolphin', emoji: '🐬', sentences: ['The dolphin is very smart.', 'A dolphin jumps high.'] },
        { english: 'chicken', emoji: '🐔', sentences: ['The chicken lays eggs.', 'I like fried chicken.'] },
        { english: 'giraffe', emoji: '🦒', sentences: ['The giraffe has a long neck.', 'A giraffe is very tall.'] },
        { english: 'elephant', emoji: '🐘', sentences: ['The elephant is huge.', 'An elephant has a long trunk.'] },
        { english: 'butterfly', emoji: '🦋', sentences: ['The butterfly is beautiful.', 'A butterfly has big wings.'] },
        { english: 'hamster', emoji: '🐹', sentences: ['The hamster is fluffy.', 'My hamster runs on a wheel.'] },
        { english: 'parrot', emoji: '🦜', sentences: ['The parrot can talk.', 'A parrot has bright colors.'] },
        { english: 'turtle', emoji: '🐢', sentences: ['The turtle moves slowly.', 'A turtle has a hard shell.'] },
        { english: 'octopus', emoji: '🐙', sentences: ['The octopus has eight arms.', 'An octopus lives in the sea.'] },
        { english: 'lobster', emoji: '🦞', sentences: ['The lobster is red.', 'A lobster lives in the ocean.'] },
        { english: 'gorilla', emoji: '🦍', sentences: ['The gorilla is strong.', 'A gorilla eats fruit.'] },
        { english: 'leopard', emoji: '🐆', sentences: ['The leopard has spots.', 'A leopard can run fast.'] },
        { english: 'peacock', emoji: '🦚', sentences: ['The peacock has pretty feathers.', 'A peacock can open its tail.'] },
      ],
    },
  },

  // ─── COLORS ───
  {
    id: 'colors',
    name: 'Colors',
    emoji: '🎨',
    words: {
      starters: [
        { english: 'red', emoji: '🔴', sentences: ['The apple is red.', 'I like red cars.'] },
        { english: 'blue', emoji: '🔵', sentences: ['The sky is blue.', 'I have a blue bag.'] },
        { english: 'pink', emoji: '🩷', sentences: ['Her dress is pink.', 'I like pink flowers.'] },
        { english: 'gray', emoji: '🩶', sentences: ['The cat is gray.', 'Clouds are gray today.'] },
        { english: 'gold', emoji: '🟡', sentences: ['The ring is gold.', 'I won a gold star.'] },
        { english: 'tan', emoji: '🟤', sentences: ['The sand is tan.', 'My shoes are tan.'] },
        { english: 'lime', emoji: '🟢', sentences: ['The lime is green.', 'I like lime color.'] },
        { english: 'ruby', emoji: '🔴', sentences: ['The ruby is red.', 'She has a ruby ring.'] },
        { english: 'aqua', emoji: '🔵', sentences: ['The pool is aqua.', 'I love aqua blue.'] },
        { english: 'rose', emoji: '🌹', sentences: ['The rose is red.', 'I like rose pink.'] },
        { english: 'jade', emoji: '🟢', sentences: ['The jade stone is green.', 'I like jade color.'] },
        { english: 'navy', emoji: '🔵', sentences: ['His shirt is navy.', 'Navy is dark blue.'] },
        { english: 'teal', emoji: '🟢', sentences: ['The teal color is pretty.', 'I like teal blue.'] },
        { english: 'plum', emoji: '🟣', sentences: ['The plum is purple.', 'I like plum color.'] },
        { english: 'wine', emoji: '🔴', sentences: ['The wine color is dark red.', 'Her bag is wine red.'] },
      ],
      movers: [
        { english: 'green', emoji: '🟢', sentences: ['The grass is green.', 'Frogs are green.'] },
        { english: 'white', emoji: '⚪', sentences: ['Snow is white.', 'The paper is white.'] },
        { english: 'black', emoji: '⚫', sentences: ['The night is black.', 'My shoes are black.'] },
        { english: 'brown', emoji: '🟤', sentences: ['The bear is brown.', 'I have brown hair.'] },
        { english: 'orange', emoji: '🟠', sentences: ['The orange is orange.', 'I like orange juice.'] },
        { english: 'purple', emoji: '🟣', sentences: ['Grapes are purple.', 'The flower is purple.'] },
        { english: 'yellow', emoji: '🟡', sentences: ['The sun is yellow.', 'Bananas are yellow.'] },
        { english: 'beige', emoji: '🟤', sentences: ['The wall is beige.', 'I have beige pants.'] },
        { english: 'peach', emoji: '🟠', sentences: ['The peach is a soft color.', 'Her cheeks are peach.'] },
        { english: 'coral', emoji: '🟠', sentences: ['The coral is pretty.', 'I like coral pink.'] },
        { english: 'cream', emoji: '⚪', sentences: ['The cream color is soft.', 'I like cream white.'] },
        { english: 'ivory', emoji: '⚪', sentences: ['The ivory is white.', 'Her dress is ivory.'] },
        { english: 'khaki', emoji: '🟤', sentences: ['He wears khaki pants.', 'Khaki is like brown.'] },
        { english: 'lilac', emoji: '🟣', sentences: ['The lilac is purple.', 'I like lilac flowers.'] },
        { english: 'amber', emoji: '🟠', sentences: ['The amber light is on.', 'Amber is a warm color.'] },
      ],
      flyers: [
        { english: 'silver', emoji: '🪙', sentences: ['The coin is silver.', 'I have a silver ring.'] },
        { english: 'golden', emoji: '✨', sentences: ['The sunset is golden.', 'She has golden hair.'] },
        { english: 'rainbow', emoji: '🌈', sentences: ['I see a rainbow in the sky.', 'A rainbow has many colors.'] },
        { english: 'crimson', emoji: '🔴', sentences: ['The rose is crimson red.', 'The sky turned crimson.'] },
        { english: 'scarlet', emoji: '🔴', sentences: ['The scarlet bird is pretty.', 'She wore a scarlet dress.'] },
        { english: 'magenta', emoji: '🟣', sentences: ['The magenta flower is bright.', 'I like magenta pink.'] },
        { english: 'indigo', emoji: '🔵', sentences: ['Indigo is a deep blue.', 'The night sky is indigo.'] },
        { english: 'maroon', emoji: '🔴', sentences: ['His shirt is maroon.', 'Maroon is dark red.'] },
        { english: 'violet', emoji: '🟣', sentences: ['The violet flower is pretty.', 'Violet is light purple.'] },
        { english: 'bronze', emoji: '🟤', sentences: ['He won a bronze medal.', 'The statue is bronze.'] },
        { english: 'copper', emoji: '🟤', sentences: ['The copper pot is shiny.', 'Copper is a warm color.'] },
        { english: 'charcoal', emoji: '⚫', sentences: ['The charcoal is dark gray.', 'I draw with charcoal.'] },
        { english: 'lavender', emoji: '🟣', sentences: ['The lavender is light purple.', 'I smell the lavender.'] },
        { english: 'burgundy', emoji: '🔴', sentences: ['Her coat is burgundy.', 'Burgundy is a deep red.'] },
        { english: 'emerald', emoji: '🟢', sentences: ['The emerald is bright green.', 'She has an emerald ring.'] },
      ],
    },
  },

  // ─── FOOD ───
  {
    id: 'food',
    name: 'Food',
    emoji: '🍽️',
    words: {
      starters: [
        { english: 'egg', emoji: '🥚', sentences: ['I eat an egg.', 'The egg is white.'] },
        { english: 'jam', emoji: '🫙', sentences: ['I like jam on bread.', 'The jam is sweet.'] },
        { english: 'pie', emoji: '🥧', sentences: ['Mom made a pie.', 'The pie is yummy.'] },
        { english: 'nut', emoji: '🥜', sentences: ['I eat a nut.', 'The nut is small.'] },
        { english: 'pea', emoji: '🫛', sentences: ['I eat a green pea.', 'The pea is round.'] },
        { english: 'ham', emoji: '🍖', sentences: ['I like ham.', 'The ham is salty.'] },
        { english: 'fig', emoji: '🫒', sentences: ['The fig is sweet.', 'I ate a fig.'] },
        { english: 'yam', emoji: '🍠', sentences: ['The yam is orange.', 'I bake a yam.'] },
        { english: 'bun', emoji: '🍞', sentences: ['I eat a bun.', 'The bun is soft.'] },
        { english: 'dip', emoji: '🥣', sentences: ['I like this dip.', 'The dip is yummy.'] },
        { english: 'tea', emoji: '🍵', sentences: ['I drink tea.', 'The tea is hot.'] },
        { english: 'oat', emoji: '🥣', sentences: ['I eat oat for breakfast.', 'Oat is good for you.'] },
        { english: 'corn', emoji: '🌽', sentences: ['I like corn.', 'The corn is yellow.'] },
        { english: 'plum', emoji: '🫐', sentences: ['The plum is sweet.', 'I ate a ripe plum.'] },
        { english: 'lime', emoji: '🍋', sentences: ['The lime is green.', 'Lime juice is sour.'] },
      ],
      movers: [
        { english: 'rice', emoji: '🍚', sentences: ['I eat rice every day.', 'Rice is white.'] },
        { english: 'milk', emoji: '🥛', sentences: ['I drink milk.', 'Milk is good for you.'] },
        { english: 'cake', emoji: '🎂', sentences: ['The cake is sweet.', 'I want birthday cake.'] },
        { english: 'apple', emoji: '🍎', sentences: ['The apple is red.', 'I eat an apple a day.'] },
        { english: 'bread', emoji: '🍞', sentences: ['I like bread and butter.', 'Bread is soft.'] },
        { english: 'water', emoji: '💧', sentences: ['I drink cold water.', 'Water is good for you.'] },
        { english: 'juice', emoji: '🧃', sentences: ['I drink orange juice.', 'Juice is sweet.'] },
        { english: 'candy', emoji: '🍬', sentences: ['The candy is sweet.', 'I love candy.'] },
        { english: 'pasta', emoji: '🍝', sentences: ['I love pasta.', 'The pasta has sauce.'] },
        { english: 'pizza', emoji: '🍕', sentences: ['I love pizza.', 'The pizza has cheese.'] },
        { english: 'salad', emoji: '🥗', sentences: ['I eat a fresh salad.', 'The salad is green.'] },
        { english: 'grape', emoji: '🍇', sentences: ['The grape is purple.', 'I eat sweet grapes.'] },
        { english: 'melon', emoji: '🍈', sentences: ['The melon is juicy.', 'I like cold melon.'] },
        { english: 'mango', emoji: '🥭', sentences: ['The mango is sweet.', 'I love mango juice.'] },
        { english: 'toast', emoji: '🍞', sentences: ['I eat toast in the morning.', 'The toast is crunchy.'] },
        { english: 'honey', emoji: '🍯', sentences: ['Honey is sweet.', 'Bees make honey.'] },
        { english: 'lemon', emoji: '🍋', sentences: ['The lemon is sour.', 'I put lemon in my water.'] },
        { english: 'berry', emoji: '🫐', sentences: ['The berry is small.', 'I pick berries.'] },
      ],
      flyers: [
        { english: 'banana', emoji: '🍌', sentences: ['The banana is yellow.', 'Monkeys love bananas.'] },
        { english: 'cheese', emoji: '🧀', sentences: ['I like cheese on pizza.', 'The mouse eats cheese.'] },
        { english: 'cookie', emoji: '🍪', sentences: ['The cookie is crunchy.', 'I baked some cookies.'] },
        { english: 'noodles', emoji: '🍜', sentences: ['I love eating noodles.', 'The noodles are hot.'] },
        { english: 'sandwich', emoji: '🥪', sentences: ['I made a sandwich.', 'The sandwich has cheese.'] },
        { english: 'pancake', emoji: '🥞', sentences: ['I eat pancakes for breakfast.', 'Pancakes are fluffy.'] },
        { english: 'popcorn', emoji: '🍿', sentences: ['I eat popcorn at the movies.', 'Popcorn is salty.'] },
        { english: 'pretzel', emoji: '🥨', sentences: ['The pretzel is twisted.', 'I like salty pretzels.'] },
        { english: 'waffle', emoji: '🧇', sentences: ['I eat waffles with syrup.', 'The waffle is crispy.'] },
        { english: 'yogurt', emoji: '🥛', sentences: ['I eat yogurt every day.', 'The yogurt is cold.'] },
        { english: 'cherry', emoji: '🍒', sentences: ['The cherry is red.', 'I like cherry pie.'] },
        { english: 'carrot', emoji: '🥕', sentences: ['The carrot is orange.', 'Rabbits eat carrots.'] },
        { english: 'potato', emoji: '🥔', sentences: ['I like baked potato.', 'The potato is brown.'] },
        { english: 'tomato', emoji: '🍅', sentences: ['The tomato is red.', 'I put tomato in my salad.'] },
        { english: 'coconut', emoji: '🥥', sentences: ['The coconut is hard.', 'I drink coconut water.'] },
        { english: 'biscuit', emoji: '🍪', sentences: ['The biscuit is crunchy.', 'I eat biscuit with tea.'] },
        { english: 'avocado', emoji: '🥑', sentences: ['The avocado is green.', 'I like avocado toast.'] },
        { english: 'sausage', emoji: '🌭', sentences: ['I eat sausage for lunch.', 'The sausage is long.'] },
      ],
    },
  },

  // ─── FAMILY ───
  {
    id: 'family',
    name: 'Family',
    emoji: '👨‍👩‍👧‍👦',
    words: {
      starters: [
        { english: 'mom', emoji: '👩', sentences: ['My mom is kind.', 'I love my mom.'] },
        { english: 'dad', emoji: '👨', sentences: ['My dad is tall.', 'Dad reads to me.'] },
        { english: 'son', emoji: '👦', sentences: ['He is her son.', 'The son is young.'] },
        { english: 'boy', emoji: '👦', sentences: ['The boy can run.', 'He is a good boy.'] },
        { english: 'girl', emoji: '👧', sentences: ['The girl can sing.', 'She is a nice girl.'] },
        { english: 'man', emoji: '👨', sentences: ['The man is tall.', 'A man walks by.'] },
        { english: 'pal', emoji: '🤝', sentences: ['He is my pal.', 'My pal is nice.'] },
        { english: 'kid', emoji: '🧒', sentences: ['The kid is happy.', 'I am a good kid.'] },
        { english: 'kin', emoji: '👨‍👩‍👧‍👦', sentences: ['They are my kin.', 'My kin lives far away.'] },
        { english: 'bro', emoji: '👦', sentences: ['He is my bro.', 'My bro is fun.'] },
        { english: 'sis', emoji: '👧', sentences: ['She is my sis.', 'My sis is kind.'] },
        { english: 'lady', emoji: '👩', sentences: ['The lady is nice.', 'A lady waves at me.'] },
        { english: 'baby', emoji: '👶', sentences: ['The baby is cute.', 'The baby is small.'] },
        { english: 'wife', emoji: '👩', sentences: ['She is his wife.', 'The wife is happy.'] },
        { english: 'mate', emoji: '🤝', sentences: ['He is my mate.', 'My mate helps me.'] },
      ],
      movers: [
        { english: 'uncle', emoji: '👨', sentences: ['My uncle is funny.', 'Uncle Tom visits us.'] },
        { english: 'aunty', emoji: '👩', sentences: ['My aunty bakes cakes.', 'Aunty May is nice.'] },
        { english: 'friend', emoji: '🤝', sentences: ['She is my best friend.', 'A good friend helps you.'] },
        { english: 'child', emoji: '🧒', sentences: ['The child is happy.', 'Every child likes to play.'] },
        { english: 'twins', emoji: '👯', sentences: ['They are twins.', 'The twins look the same.'] },
        { english: 'niece', emoji: '👧', sentences: ['My niece is seven.', 'I play with my niece.'] },
        { english: 'queen', emoji: '👸', sentences: ['The queen wears a crown.', 'She looks like a queen.'] },
        { english: 'prince', emoji: '🤴', sentences: ['The prince is brave.', 'A prince lives in a castle.'] },
        { english: 'elder', emoji: '👴', sentences: ['My elder is wise.', 'We respect our elders.'] },
        { english: 'guest', emoji: '🧑', sentences: ['The guest is here.', 'We welcome our guest.'] },
        { english: 'couple', emoji: '👫', sentences: ['The couple is happy.', 'A couple walks in the park.'] },
        { english: 'parent', emoji: '👨‍👩‍👧', sentences: ['My parent helps me.', 'A parent loves their child.'] },
        { english: 'nephew', emoji: '👦', sentences: ['My nephew is five.', 'I play with my nephew.'] },
        { english: 'granny', emoji: '👵', sentences: ['Granny tells stories.', 'I visit granny on Sunday.'] },
        { english: 'youth', emoji: '🧒', sentences: ['The youth is strong.', 'Youth is full of energy.'] },
      ],
      flyers: [
        { english: 'sister', emoji: '👧', sentences: ['My sister is older.', 'I play with my sister.'] },
        { english: 'brother', emoji: '👦', sentences: ['My brother is funny.', 'I have one brother.'] },
        { english: 'grandma', emoji: '👵', sentences: ['Grandma tells stories.', 'I visit grandma on Sunday.'] },
        { english: 'grandpa', emoji: '👴', sentences: ['Grandpa plays chess.', 'I love my grandpa.'] },
        { english: 'parents', emoji: '👫', sentences: ['My parents love me.', 'Parents take care of us.'] },
        { english: 'daughter', emoji: '👧', sentences: ['She is their daughter.', 'The daughter helps mom.'] },
        { english: 'husband', emoji: '👨', sentences: ['He is her husband.', 'The husband cooks dinner.'] },
        { english: 'cousin', emoji: '🧑', sentences: ['My cousin visits in summer.', 'I play with my cousin.'] },
        { english: 'toddler', emoji: '👶', sentences: ['The toddler is learning to walk.', 'A toddler is very small.'] },
        { english: 'grandchild', emoji: '🧒', sentences: ['She is my grandchild.', 'I love my grandchild.'] },
        { english: 'princess', emoji: '👸', sentences: ['The princess is kind.', 'She looks like a princess.'] },
        { english: 'neighbor', emoji: '🏠', sentences: ['My neighbor is friendly.', 'The neighbor has a dog.'] },
        { english: 'family', emoji: '👨‍👩‍👧‍👦', sentences: ['I love my family.', 'My family is big.'] },
        { english: 'sibling', emoji: '👧', sentences: ['She is my sibling.', 'I have two siblings.'] },
        { english: 'relative', emoji: '👨‍👩‍👧‍👦', sentences: ['My relative lives far away.', 'We visit our relatives.'] },
      ],
    },
  },

  // ─── BODY ───
  {
    id: 'body',
    name: 'Body',
    emoji: '🧍',
    words: {
      starters: [
        { english: 'eye', emoji: '👁️', sentences: ['I see with my eye.', 'She has blue eyes.'] },
        { english: 'ear', emoji: '👂', sentences: ['I hear with my ear.', 'The ear is small.'] },
        { english: 'arm', emoji: '💪', sentences: ['I wave my arm.', 'My arm is strong.'] },
        { english: 'leg', emoji: '🦵', sentences: ['I run with my legs.', 'My leg is long.'] },
        { english: 'toe', emoji: '🦶', sentences: ['I have ten toes.', 'My toe is small.'] },
        { english: 'lip', emoji: '👄', sentences: ['My lip is dry.', 'She has pink lips.'] },
        { english: 'rib', emoji: '🦴', sentences: ['I can feel my rib.', 'A rib is a bone.'] },
        { english: 'hip', emoji: '🦴', sentences: ['I put my hand on my hip.', 'My hip is sore.'] },
        { english: 'jaw', emoji: '🦷', sentences: ['I move my jaw to eat.', 'My jaw is strong.'] },
        { english: 'gum', emoji: '🦷', sentences: ['My gum is pink.', 'I brush my gums.'] },
        { english: 'back', emoji: '🔙', sentences: ['My back is straight.', 'I lie on my back.'] },
        { english: 'bone', emoji: '🦴', sentences: ['A bone is hard.', 'The dog has a bone.'] },
        { english: 'face', emoji: '😊', sentences: ['I wash my face.', 'She has a happy face.'] },
        { english: 'neck', emoji: '🧣', sentences: ['My neck is long.', 'I wear a scarf on my neck.'] },
        { english: 'shin', emoji: '🦵', sentences: ['I bumped my shin.', 'My shin is sore.'] },
      ],
      movers: [
        { english: 'head', emoji: '🗣️', sentences: ['I wear a hat on my head.', 'Nod your head yes.'] },
        { english: 'nose', emoji: '👃', sentences: ['I smell with my nose.', 'My nose is cold.'] },
        { english: 'mouth', emoji: '👄', sentences: ['I eat with my mouth.', 'Open your mouth wide.'] },
        { english: 'hand', emoji: '✋', sentences: ['I write with my hand.', 'Wave your hand hello.'] },
        { english: 'foot', emoji: '🦶', sentences: ['I walk with my feet.', 'My foot is big.'] },
        { english: 'hair', emoji: '💇', sentences: ['I brush my hair.', 'Her hair is long.'] },
        { english: 'teeth', emoji: '🦷', sentences: ['I brush my teeth.', 'My teeth are white.'] },
        { english: 'thumb', emoji: '👍', sentences: ['I give a thumbs up.', 'My thumb is short.'] },
        { english: 'cheek', emoji: '😊', sentences: ['My cheek is soft.', 'She kissed my cheek.'] },
        { english: 'wrist', emoji: '⌚', sentences: ['I wear a watch on my wrist.', 'My wrist is thin.'] },
        { english: 'chest', emoji: '🫁', sentences: ['I put my hand on my chest.', 'My chest is strong.'] },
        { english: 'brain', emoji: '🧠', sentences: ['I think with my brain.', 'The brain is very smart.'] },
        { english: 'heart', emoji: '❤️', sentences: ['My heart beats fast.', 'I love with my heart.'] },
        { english: 'ankle', emoji: '🦶', sentences: ['I twist my ankle.', 'My ankle is sore.'] },
        { english: 'palm', emoji: '🤚', sentences: ['I hold it in my palm.', 'My palm is warm.'] },
        { english: 'belly', emoji: '🤰', sentences: ['My belly is full.', 'The baby has a round belly.'] },
      ],
      flyers: [
        { english: 'finger', emoji: '☝️', sentences: ['I point with my finger.', 'I have ten fingers.'] },
        { english: 'elbow', emoji: '💪', sentences: ['I bump my elbow.', 'Bend your elbow.'] },
        { english: 'tongue', emoji: '👅', sentences: ['I taste with my tongue.', 'Stick out your tongue.'] },
        { english: 'shoulder', emoji: '🦺', sentences: ['My shoulder is sore.', 'Shrug your shoulders.'] },
        { english: 'stomach', emoji: '🤰', sentences: ['My stomach is full.', 'My stomach hurts a little.'] },
        { english: 'forehead', emoji: '😊', sentences: ['Touch your forehead.', 'My forehead is warm.'] },
        { english: 'eyebrow', emoji: '🤨', sentences: ['I raise my eyebrow.', 'My eyebrows are dark.'] },
        { english: 'nostril', emoji: '👃', sentences: ['I have two nostrils.', 'Air goes in my nostril.'] },
        { english: 'eyelash', emoji: '👁️', sentences: ['My eyelash is long.', 'I blink my eyelashes.'] },
        { english: 'toenail', emoji: '🦶', sentences: ['I cut my toenail.', 'My toenail is short.'] },
        { english: 'knuckle', emoji: '✊', sentences: ['I knock with my knuckle.', 'My knuckle is bony.'] },
        { english: 'muscle', emoji: '💪', sentences: ['I flex my muscle.', 'My muscle is strong.'] },
        { english: 'temple', emoji: '😊', sentences: ['I rub my temple.', 'My temple is on my head.'] },
        { english: 'dimple', emoji: '😊', sentences: ['She has a cute dimple.', 'A dimple shows when I smile.'] },
        { english: 'freckle', emoji: '😊', sentences: ['I have a freckle on my nose.', 'Freckles are cute.'] },
      ],
    },
  },

  // ─── NUMBERS ───
  {
    id: 'numbers',
    name: 'Numbers',
    emoji: '🔢',
    words: {
      starters: [
        { english: 'one', emoji: '1️⃣', sentences: ['I have one nose.', 'One plus one is two.'] },
        { english: 'two', emoji: '2️⃣', sentences: ['I have two hands.', 'Two cats are playing.'] },
        { english: 'six', emoji: '6️⃣', sentences: ['I am six years old.', 'Six is after five.'] },
        { english: 'ten', emoji: '🔟', sentences: ['I have ten fingers.', 'Count to ten.'] },
        { english: 'few', emoji: '🔢', sentences: ['I have a few toys.', 'A few birds are singing.'] },
        { english: 'all', emoji: '🔢', sentences: ['I ate all my food.', 'All the kids are here.'] },
        { english: 'half', emoji: '🔢', sentences: ['I ate half the cake.', 'Half of ten is five.'] },
        { english: 'pair', emoji: '🔢', sentences: ['I have a pair of shoes.', 'A pair means two.'] },
        { english: 'zero', emoji: '0️⃣', sentences: ['Zero means nothing.', 'I have zero pets.'] },
        { english: 'once', emoji: '1️⃣', sentences: ['I go once a week.', 'I will try once more.'] },
        { english: 'many', emoji: '🔢', sentences: ['I have many books.', 'Many kids like ice cream.'] },
        { english: 'both', emoji: '2️⃣', sentences: ['Both cats are cute.', 'I like both colors.'] },
        { english: 'more', emoji: '➕', sentences: ['I want more cake.', 'Can I have more milk?'] },
        { english: 'less', emoji: '➖', sentences: ['I want less sugar.', 'Less is sometimes more.'] },
        { english: 'some', emoji: '🔢', sentences: ['I want some water.', 'Some birds can swim.'] },
      ],
      movers: [
        { english: 'three', emoji: '3️⃣', sentences: ['I have three books.', 'A triangle has three sides.'] },
        { english: 'four', emoji: '4️⃣', sentences: ['A dog has four legs.', 'There are four seasons.'] },
        { english: 'five', emoji: '5️⃣', sentences: ['I have five pencils.', 'High five!'] },
        { english: 'seven', emoji: '7️⃣', sentences: ['There are seven days.', 'I am seven years old.'] },
        { english: 'eight', emoji: '8️⃣', sentences: ['The spider has eight legs.', 'I wake up at eight.'] },
        { english: 'nine', emoji: '9️⃣', sentences: ['Nine is before ten.', 'I have nine crayons.'] },
        { english: 'first', emoji: '🥇', sentences: ['I am first in line.', 'The first day of school.'] },
        { english: 'third', emoji: '🥉', sentences: ['I am in third grade.', 'The third one is mine.'] },
        { english: 'twice', emoji: '2️⃣', sentences: ['I brush my teeth twice a day.', 'I went there twice.'] },
        { english: 'dozen', emoji: '🔢', sentences: ['A dozen eggs is twelve.', 'I ate a dozen cookies.'] },
        { english: 'total', emoji: '🔢', sentences: ['The total is twenty.', 'What is the total?'] },
        { english: 'count', emoji: '🔢', sentences: ['Can you count to ten?', 'I count the stars.'] },
        { english: 'every', emoji: '🔢', sentences: ['I go to school every day.', 'Every kid got a prize.'] },
        { english: 'minus', emoji: '➖', sentences: ['Ten minus five is five.', 'Minus means take away.'] },
        { english: 'equal', emoji: '🟰', sentences: ['Two plus two is equal to four.', 'We are all equal.'] },
      ],
      flyers: [
        { english: 'eleven', emoji: '1️⃣', sentences: ['There are eleven players.', 'Eleven comes after ten.'] },
        { english: 'twelve', emoji: '1️⃣', sentences: ['There are twelve months.', 'Twelve eggs in a dozen.'] },
        { english: 'twenty', emoji: '2️⃣', sentences: ['I can count to twenty.', 'Twenty is two tens.'] },
        { english: 'hundred', emoji: '💯', sentences: ['A hundred is a big number.', 'I scored a hundred points.'] },
        { english: 'thousand', emoji: '🔢', sentences: ['A thousand is very many.', 'There are a thousand stars.'] },
        { english: 'thirteen', emoji: '1️⃣', sentences: ['Thirteen is after twelve.', 'I have thirteen cards.'] },
        { english: 'fifteen', emoji: '1️⃣', sentences: ['Fifteen minutes to go.', 'I counted fifteen birds.'] },
        { english: 'sixteen', emoji: '1️⃣', sentences: ['Sixteen is a big number.', 'I have sixteen books.'] },
        { english: 'million', emoji: '🔢', sentences: ['A million is very big.', 'I wish for a million stars.'] },
        { english: 'billion', emoji: '🔢', sentences: ['A billion is a huge number.', 'There are billions of stars.'] },
        { english: 'quarter', emoji: '🔢', sentences: ['A quarter is one fourth.', 'I ate a quarter of the pie.'] },
        { english: 'second', emoji: '🥈', sentences: ['I came in second place.', 'Wait one second please.'] },
        { english: 'double', emoji: '✌️', sentences: ['Double means two times.', 'I got a double scoop.'] },
        { english: 'triple', emoji: '3️⃣', sentences: ['Triple means three times.', 'I did a triple jump.'] },
        { english: 'percent', emoji: '🔢', sentences: ['I got a hundred percent.', 'Fifty percent is half.'] },
      ],
    },
  },

  // ─── SCHOOL ───
  {
    id: 'school',
    name: 'School',
    emoji: '🏫',
    words: {
      starters: [
        { english: 'pen', emoji: '🖊️', sentences: ['I write with a pen.', 'The pen is blue.'] },
        { english: 'bag', emoji: '🎒', sentences: ['I carry my bag.', 'My bag is heavy.'] },
        { english: 'map', emoji: '🗺️', sentences: ['I look at the map.', 'The map shows the world.'] },
        { english: 'book', emoji: '📖', sentences: ['I read a book.', 'The book is fun.'] },
        { english: 'desk', emoji: '🪑', sentences: ['I sit at my desk.', 'My desk is clean.'] },
        { english: 'bell', emoji: '🔔', sentences: ['The bell rings.', 'I hear the bell.'] },
        { english: 'test', emoji: '📝', sentences: ['I take a test.', 'The test is easy.'] },
        { english: 'art', emoji: '🎨', sentences: ['I love art class.', 'Art is fun.'] },
        { english: 'bus', emoji: '🚌', sentences: ['I ride the bus.', 'The bus is yellow.'] },
        { english: 'cap', emoji: '🧢', sentences: ['I wear a cap.', 'My cap is red.'] },
        { english: 'cup', emoji: '🥤', sentences: ['I drink from a cup.', 'The cup is full.'] },
        { english: 'gym', emoji: '🏋️', sentences: ['I play in the gym.', 'The gym is big.'] },
        { english: 'note', emoji: '📝', sentences: ['I write a note.', 'The note is short.'] },
        { english: 'page', emoji: '📄', sentences: ['Turn the page.', 'This page is blank.'] },
        { english: 'rule', emoji: '📏', sentences: ['I follow the rule.', 'Rules keep us safe.'] },
      ],
      movers: [
        { english: 'chalk', emoji: '🖍️', sentences: ['I draw with chalk.', 'The chalk is white.'] },
        { english: 'chair', emoji: '🪑', sentences: ['I sit on a chair.', 'The chair is brown.'] },
        { english: 'class', emoji: '🏫', sentences: ['I go to class.', 'My class has twenty kids.'] },
        { english: 'ruler', emoji: '📏', sentences: ['I measure with a ruler.', 'The ruler is long.'] },
        { english: 'eraser', emoji: '🧹', sentences: ['I use an eraser.', 'The eraser is pink.'] },
        { english: 'pencil', emoji: '✏️', sentences: ['I write with a pencil.', 'My pencil is sharp.'] },
        { english: 'paper', emoji: '📄', sentences: ['I draw on paper.', 'The paper is white.'] },
        { english: 'grade', emoji: '📊', sentences: ['I got a good grade.', 'I am in second grade.'] },
        { english: 'lunch', emoji: '🍱', sentences: ['I eat lunch at noon.', 'My lunch box is blue.'] },
        { english: 'board', emoji: '📋', sentences: ['The teacher writes on the board.', 'The board is green.'] },
        { english: 'clock', emoji: '🕐', sentences: ['I look at the clock.', 'The clock says noon.'] },
        { english: 'table', emoji: '🪑', sentences: ['We sit at a table.', 'The table is round.'] },
        { english: 'story', emoji: '📖', sentences: ['I read a story.', 'The story is funny.'] },
        { english: 'quiz', emoji: '📝', sentences: ['We have a quiz today.', 'The quiz was easy.'] },
        { english: 'globe', emoji: '🌍', sentences: ['I spin the globe.', 'The globe shows the Earth.'] },
      ],
      flyers: [
        { english: 'teacher', emoji: '👩‍🏫', sentences: ['My teacher is kind.', 'The teacher reads to us.'] },
        { english: 'student', emoji: '🧑‍🎓', sentences: ['I am a good student.', 'The student raises a hand.'] },
        { english: 'school', emoji: '🏫', sentences: ['I walk to school.', 'School starts at eight.'] },
        { english: 'library', emoji: '📚', sentences: ['I read in the library.', 'The library has many books.'] },
        { english: 'science', emoji: '🔬', sentences: ['I love science class.', 'Science is about nature.'] },
        { english: 'lesson', emoji: '📖', sentences: ['The lesson is about math.', 'I learn a new lesson.'] },
        { english: 'project', emoji: '📋', sentences: ['I work on a project.', 'My project is about space.'] },
        { english: 'crayon', emoji: '🖍️', sentences: ['I color with a crayon.', 'The crayon is red.'] },
        { english: 'recess', emoji: '🏃', sentences: ['I play at recess.', 'Recess is my favorite time.'] },
        { english: 'notebook', emoji: '📓', sentences: ['I write in my notebook.', 'My notebook is blue.'] },
        { english: 'homework', emoji: '📝', sentences: ['I do my homework.', 'Homework is done after school.'] },
        { english: 'backpack', emoji: '🎒', sentences: ['I carry my backpack.', 'My backpack is green.'] },
        { english: 'scissors', emoji: '✂️', sentences: ['I cut with scissors.', 'The scissors are sharp.'] },
        { english: 'textbook', emoji: '📕', sentences: ['I read the textbook.', 'My textbook is heavy.'] },
        { english: 'alphabet', emoji: '🔤', sentences: ['I know the alphabet.', 'The alphabet has 26 letters.'] },
        { english: 'spelling', emoji: '📝', sentences: ['I am good at spelling.', 'We have a spelling test.'] },
      ],
    },
  },

  // ─── CLOTHES ───
  {
    id: 'clothes',
    name: 'Clothes',
    emoji: '👗',
    words: {
      starters: [
        { english: 'hat', emoji: '🎩', sentences: ['I wear a hat.', 'The hat is big.'] },
        { english: 'cap', emoji: '🧢', sentences: ['I wear a red cap.', 'My cap keeps the sun out.'] },
        { english: 'tie', emoji: '👔', sentences: ['Dad wears a tie.', 'The tie is blue.'] },
        { english: 'top', emoji: '👚', sentences: ['I wear a nice top.', 'My top is pink.'] },
        { english: 'belt', emoji: '🪢', sentences: ['I wear a belt.', 'The belt is brown.'] },
        { english: 'boot', emoji: '🥾', sentences: ['I wear a boot.', 'My boot is warm.'] },
        { english: 'coat', emoji: '🧥', sentences: ['I put on my coat.', 'The coat is warm.'] },
        { english: 'gown', emoji: '👗', sentences: ['She wears a gown.', 'The gown is long.'] },
        { english: 'vest', emoji: '🦺', sentences: ['I wear a vest.', 'The vest is warm.'] },
        { english: 'sock', emoji: '🧦', sentences: ['I put on a sock.', 'My sock is white.'] },
        { english: 'shoe', emoji: '👟', sentences: ['I tie my shoe.', 'My shoe is new.'] },
        { english: 'ring', emoji: '💍', sentences: ['She wears a ring.', 'The ring is gold.'] },
        { english: 'bib', emoji: '🍼', sentences: ['The baby wears a bib.', 'The bib is messy.'] },
        { english: 'robe', emoji: '👘', sentences: ['I wear a robe.', 'The robe is soft.'] },
        { english: 'hood', emoji: '🧥', sentences: ['I pull up my hood.', 'The hood keeps me dry.'] },
      ],
      movers: [
        { english: 'shirt', emoji: '👕', sentences: ['I wear a white shirt.', 'My shirt is clean.'] },
        { english: 'pants', emoji: '👖', sentences: ['I put on my pants.', 'My pants are blue.'] },
        { english: 'dress', emoji: '👗', sentences: ['She wears a pretty dress.', 'The dress is red.'] },
        { english: 'skirt', emoji: '👗', sentences: ['I wear a skirt.', 'The skirt is short.'] },
        { english: 'scarf', emoji: '🧣', sentences: ['I wear a warm scarf.', 'The scarf is long.'] },
        { english: 'glove', emoji: '🧤', sentences: ['I wear a glove.', 'The glove keeps me warm.'] },
        { english: 'jeans', emoji: '👖', sentences: ['I wear blue jeans.', 'My jeans are new.'] },
        { english: 'apron', emoji: '👨‍🍳', sentences: ['Mom wears an apron.', 'The apron is white.'] },
        { english: 'badge', emoji: '📛', sentences: ['I wear a name badge.', 'The badge is round.'] },
        { english: 'shorts', emoji: '🩳', sentences: ['I wear shorts in summer.', 'My shorts are green.'] },
        { english: 'blouse', emoji: '👚', sentences: ['She wears a blouse.', 'The blouse is pretty.'] },
        { english: 'blazer', emoji: '🧥', sentences: ['He wears a blazer.', 'The blazer is dark.'] },
        { english: 'sandal', emoji: '👡', sentences: ['I wear sandals at the beach.', 'My sandal is brown.'] },
        { english: 'hoodie', emoji: '🧥', sentences: ['I wear my hoodie.', 'The hoodie is cozy.'] },
        { english: 'bonnet', emoji: '🎀', sentences: ['The baby wears a bonnet.', 'The bonnet is white.'] },
      ],
      flyers: [
        { english: 'jacket', emoji: '🧥', sentences: ['I wear a warm jacket.', 'My jacket has pockets.'] },
        { english: 'sweater', emoji: '🧥', sentences: ['The sweater is cozy.', 'I wear a sweater when it is cold.'] },
        { english: 'mittens', emoji: '🧤', sentences: ['I wear mittens in winter.', 'My mittens are red.'] },
        { english: 'uniform', emoji: '👔', sentences: ['I wear a school uniform.', 'The uniform is blue.'] },
        { english: 'pajamas', emoji: '🛏️', sentences: ['I wear pajamas to bed.', 'My pajamas have stars.'] },
        { english: 'sneaker', emoji: '👟', sentences: ['I run in my sneakers.', 'My sneaker is white.'] },
        { english: 'slipper', emoji: '🥿', sentences: ['I wear slippers at home.', 'My slipper is soft.'] },
        { english: 'raincoat', emoji: '🧥', sentences: ['I wear a raincoat when it rains.', 'The raincoat is yellow.'] },
        { english: 'necklace', emoji: '📿', sentences: ['She wears a necklace.', 'The necklace is pretty.'] },
        { english: 'bracelet', emoji: '📿', sentences: ['I wear a bracelet.', 'The bracelet is silver.'] },
        { english: 'swimsuit', emoji: '🩱', sentences: ['I wear a swimsuit to the pool.', 'My swimsuit is blue.'] },
        { english: 'leggings', emoji: '👖', sentences: ['She wears black leggings.', 'Leggings are comfortable.'] },
        { english: 'overalls', emoji: '👖', sentences: ['I wear overalls to paint.', 'My overalls are blue.'] },
        { english: 'cardigan', emoji: '🧥', sentences: ['I wear a cardigan.', 'The cardigan is soft.'] },
        { english: 'earring', emoji: '💎', sentences: ['She wears an earring.', 'The earring is shiny.'] },
      ],
    },
  },

  // ─── WEATHER ───
  {
    id: 'weather',
    name: 'Weather',
    emoji: '🌤️',
    words: {
      starters: [
        { english: 'sun', emoji: '☀️', sentences: ['The sun is bright.', 'I like the warm sun.'] },
        { english: 'fog', emoji: '🌫️', sentences: ['The fog is thick.', 'I cannot see in the fog.'] },
        { english: 'ice', emoji: '🧊', sentences: ['The ice is cold.', 'I slip on the ice.'] },
        { english: 'wet', emoji: '💧', sentences: ['The grass is wet.', 'My shoes are wet.'] },
        { english: 'hot', emoji: '🔥', sentences: ['It is very hot today.', 'The sun is hot.'] },
        { english: 'cold', emoji: '🥶', sentences: ['It is cold outside.', 'I feel cold today.'] },
        { english: 'wind', emoji: '💨', sentences: ['The wind is strong.', 'Wind blows the leaves.'] },
        { english: 'rain', emoji: '🌧️', sentences: ['The rain is heavy.', 'I play in the rain.'] },
        { english: 'snow', emoji: '❄️', sentences: ['The snow is white.', 'I play in the snow.'] },
        { english: 'hail', emoji: '🌨️', sentences: ['Hail falls from the sky.', 'Hail is like ice balls.'] },
        { english: 'dew', emoji: '💧', sentences: ['The dew is on the grass.', 'Dew comes in the morning.'] },
        { english: 'warm', emoji: '🌡️', sentences: ['It is warm today.', 'The water is warm.'] },
        { english: 'cool', emoji: '🌡️', sentences: ['The air is cool.', 'It is a cool day.'] },
        { english: 'dry', emoji: '☀️', sentences: ['The land is dry.', 'It is a dry day.'] },
        { english: 'haze', emoji: '🌫️', sentences: ['The haze is in the air.', 'I see haze in the sky.'] },
      ],
      movers: [
        { english: 'cloud', emoji: '☁️', sentences: ['The cloud is white.', 'A cloud hides the sun.'] },
        { english: 'storm', emoji: '⛈️', sentences: ['The storm is loud.', 'A storm brings rain.'] },
        { english: 'frost', emoji: '❄️', sentences: ['The frost is on the window.', 'Frost makes the ground white.'] },
        { english: 'windy', emoji: '💨', sentences: ['It is very windy today.', 'My hat blew off in the windy weather.'] },
        { english: 'sunny', emoji: '☀️', sentences: ['It is a sunny day.', 'I play outside when it is sunny.'] },
        { english: 'rainy', emoji: '🌧️', sentences: ['It is a rainy day.', 'I stay inside on rainy days.'] },
        { english: 'snowy', emoji: '🌨️', sentences: ['It is snowy outside.', 'I love snowy days.'] },
        { english: 'foggy', emoji: '🌫️', sentences: ['It is foggy this morning.', 'The foggy day is gray.'] },
        { english: 'cloudy', emoji: '☁️', sentences: ['It is cloudy today.', 'The cloudy sky is gray.'] },
        { english: 'humid', emoji: '💧', sentences: ['The air is humid.', 'Humid days feel sticky.'] },
        { english: 'flood', emoji: '🌊', sentences: ['The flood covers the road.', 'A flood has lots of water.'] },
        { english: 'breeze', emoji: '💨', sentences: ['The breeze is gentle.', 'A breeze cools me down.'] },
        { english: 'freeze', emoji: '🥶', sentences: ['The water will freeze.', 'It is cold enough to freeze.'] },
        { english: 'degree', emoji: '🌡️', sentences: ['It is thirty degrees today.', 'The degree is very high.'] },
        { english: 'sleet', emoji: '🌨️', sentences: ['Sleet falls from the sky.', 'Sleet is rain and ice.'] },
      ],
      flyers: [
        { english: 'rainbow', emoji: '🌈', sentences: ['A rainbow appears after rain.', 'The rainbow has seven colors.'] },
        { english: 'thunder', emoji: '⚡', sentences: ['The thunder is very loud.', 'Thunder comes after lightning.'] },
        { english: 'weather', emoji: '🌤️', sentences: ['The weather is nice today.', 'I check the weather every day.'] },
        { english: 'tornado', emoji: '🌪️', sentences: ['A tornado is a big storm.', 'The tornado spins fast.'] },
        { english: 'drought', emoji: '☀️', sentences: ['A drought means no rain.', 'The drought made the land dry.'] },
        { english: 'drizzle', emoji: '🌧️', sentences: ['A light drizzle is falling.', 'The drizzle is gentle.'] },
        { english: 'monsoon', emoji: '🌧️', sentences: ['The monsoon brings heavy rain.', 'Monsoon season is very wet.'] },
        { english: 'blizzard', emoji: '🌨️', sentences: ['The blizzard has strong wind.', 'A blizzard brings lots of snow.'] },
        { english: 'sunshine', emoji: '☀️', sentences: ['The sunshine is warm.', 'I love the bright sunshine.'] },
        { english: 'forecast', emoji: '📺', sentences: ['I watch the weather forecast.', 'The forecast says it will rain.'] },
        { english: 'snowfall', emoji: '❄️', sentences: ['The snowfall is heavy.', 'I watch the snowfall outside.'] },
        { english: 'sunrise', emoji: '🌅', sentences: ['The sunrise is pretty.', 'I wake up at sunrise.'] },
        { english: 'sunset', emoji: '🌇', sentences: ['The sunset is orange.', 'I watch the sunset.'] },
        { english: 'climate', emoji: '🌍', sentences: ['The climate is warm here.', 'Climate can change slowly.'] },
        { english: 'moisture', emoji: '💧', sentences: ['There is moisture in the air.', 'Moisture makes things wet.'] },
        { english: 'cyclone', emoji: '🌀', sentences: ['A cyclone is a big storm.', 'The cyclone has strong winds.'] },
      ],
    },
  },

  // ─── ACTIONS ───
  {
    id: 'actions',
    name: 'Actions',
    emoji: '🏃',
    words: {
      starters: [
        { english: 'run', emoji: '🏃', sentences: ['I run to school.', 'The dog can run fast.'] },
        { english: 'eat', emoji: '🍽️', sentences: ['I eat an apple.', 'We eat lunch at noon.'] },
        { english: 'sit', emoji: '🪑', sentences: ['I sit on a chair.', 'Sit down please.'] },
        { english: 'see', emoji: '👀', sentences: ['I see a bird.', 'Can you see the stars?'] },
        { english: 'cry', emoji: '😢', sentences: ['The baby will cry.', 'Do not cry.'] },
        { english: 'fly', emoji: '🕊️', sentences: ['Birds can fly.', 'I want to fly a kite.'] },
        { english: 'cut', emoji: '✂️', sentences: ['I cut the paper.', 'Mom will cut the cake.'] },
        { english: 'hop', emoji: '🐰', sentences: ['I hop like a bunny.', 'Hop on one foot.'] },
        { english: 'hug', emoji: '🤗', sentences: ['I hug my mom.', 'Give me a big hug.'] },
        { english: 'ask', emoji: '❓', sentences: ['I ask a question.', 'Ask your teacher.'] },
        { english: 'mix', emoji: '🥣', sentences: ['I mix the colors.', 'Mix the batter well.'] },
        { english: 'nap', emoji: '😴', sentences: ['The baby takes a nap.', 'I take a short nap.'] },
        { english: 'dig', emoji: '⛏️', sentences: ['I dig in the sand.', 'The dog likes to dig.'] },
        { english: 'win', emoji: '🏆', sentences: ['I want to win the game.', 'She will win the race.'] },
        { english: 'try', emoji: '💪', sentences: ['I try my best.', 'Try it one more time.'] },
      ],
      movers: [
        { english: 'jump', emoji: '🤸', sentences: ['I jump over the puddle.', 'Jump up high!'] },
        { english: 'swim', emoji: '🏊', sentences: ['I swim in the pool.', 'Fish swim in the water.'] },
        { english: 'read', emoji: '📖', sentences: ['I read a book.', 'Can you read this word?'] },
        { english: 'sing', emoji: '🎤', sentences: ['I sing a song.', 'Birds sing in the morning.'] },
        { english: 'draw', emoji: '✏️', sentences: ['I draw a picture.', 'She can draw very well.'] },
        { english: 'write', emoji: '✍️', sentences: ['I write my name.', 'Write the answer down.'] },
        { english: 'dance', emoji: '💃', sentences: ['I dance to music.', 'She loves to dance.'] },
        { english: 'climb', emoji: '🧗', sentences: ['I climb the tree.', 'Monkeys climb fast.'] },
        { english: 'drink', emoji: '🥤', sentences: ['I drink water.', 'Drink your milk.'] },
        { english: 'sleep', emoji: '😴', sentences: ['I sleep at night.', 'The cat likes to sleep.'] },
        { english: 'laugh', emoji: '😂', sentences: ['I laugh at the joke.', 'We all laugh together.'] },
        { english: 'smile', emoji: '😊', sentences: ['I smile at my friend.', 'She has a nice smile.'] },
        { english: 'throw', emoji: '🤾', sentences: ['I throw the ball.', 'Throw it to me!'] },
        { english: 'catch', emoji: '🤲', sentences: ['I catch the ball.', 'Can you catch this?'] },
        { english: 'paint', emoji: '🎨', sentences: ['I paint a picture.', 'She can paint flowers.'] },
        { english: 'build', emoji: '🧱', sentences: ['I build a tower.', 'We build a sandcastle.'] },
        { english: 'count', emoji: '🔢', sentences: ['I count to ten.', 'Count the apples.'] },
        { english: 'carry', emoji: '📦', sentences: ['I carry my bag.', 'Can you carry this box?'] },
      ],
      flyers: [
        { english: 'listen', emoji: '👂', sentences: ['I listen to the teacher.', 'Listen to the birds sing.'] },
        { english: 'whisper', emoji: '🤫', sentences: ['I whisper in her ear.', 'Please whisper in the library.'] },
        { english: 'explore', emoji: '🔍', sentences: ['I explore the forest.', 'We love to explore new places.'] },
        { english: 'imagine', emoji: '💭', sentences: ['I imagine a big castle.', 'Imagine you can fly.'] },
        { english: 'collect', emoji: '🧺', sentences: ['I collect seashells.', 'She collects stickers.'] },
        { english: 'measure', emoji: '📏', sentences: ['I measure the table.', 'Measure how tall you are.'] },
        { english: 'balance', emoji: '⚖️', sentences: ['I balance on one foot.', 'Balance the book on your head.'] },
        { english: 'whistle', emoji: '🎵', sentences: ['I whistle a happy song.', 'Can you whistle?'] },
        { english: 'stretch', emoji: '🤸', sentences: ['I stretch before I run.', 'Stretch your arms up high.'] },
        { english: 'squeeze', emoji: '🤏', sentences: ['I squeeze the lemon.', 'Squeeze my hand.'] },
        { english: 'stumble', emoji: '🚶', sentences: ['I stumble on the rock.', 'Be careful not to stumble.'] },
        { english: 'clap', emoji: '👏', sentences: ['I clap my hands.', 'We clap after the show.'] },
        { english: 'shout', emoji: '📣', sentences: ['I shout for help.', 'Do not shout inside.'] },
        { english: 'discover', emoji: '🔍', sentences: ['I discover a new bug.', 'We discover a secret path.'] },
        { english: 'practice', emoji: '🎯', sentences: ['I practice the piano.', 'Practice makes you better.'] },
        { english: 'remember', emoji: '🧠', sentences: ['I remember your name.', 'Remember to bring your book.'] },
        { english: 'celebrate', emoji: '🎉', sentences: ['We celebrate her birthday.', 'Let us celebrate together.'] },
        { english: 'organize', emoji: '📋', sentences: ['I organize my room.', 'She likes to organize her desk.'] },
      ],
    },
  },
]

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

/** Get words for a specific level from a category */
export function getWords(category: Category, level: Level): Word[] {
  return category.words[level]
}
